### ISSUE TITLE
Crash when giving HTTPDialer non-prefixed URI

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/go-loom#348]
Stack trace: 

```
[~/go/src/github.com/loomnetwork/transfer-gateway-v2/tmp/loom-123, 127, cleanup+7]: $GOPATH/src/github.com/loomnetwork/loomchain/loom call list_validatorsV2 -r 127.0.0.1:60597/query
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x46bf22e]

goroutine 1 [running]:
github.com/loomnetwork/go-loom/client.newHTTPDialer(0x7ffeefbff8b6, 0x15, 0xc000189c20)
        /Users/gakonst/go/src/github.com/loomnetwork/go-loom/client/rpc_client.go:58 +0x3e
github.com/loomnetwork/go-loom/client.NewJSONRPCClientShareTransport(0x7ffeefbff8b6, 0x15, 0xc000189c20, 0xc000956dc0)
        /Users/gakonst/go/src/github.com/loomnetwork/go-loom/client/rpc_client.go:77 +0x4d
github.com/loomnetwork/go-loom/client.NewJSONRPCClient(0x7ffeefbff8b6, 0x15, 0xc000956dc0)
        /Users/gakonst/go/src/github.com/loomnetwork/go-loom/client/rpc_client.go:73 +0x4f
github.com/loomnetwork/go-loom/client.NewDAppChainRPCClient(0x5019812, 0x7, 0x505512f, 0x1a, 0x7ffeefbff8b6, 0x15, 0x5)
        /Users/gakonst/go/src/github.com/loomnetwork/go-loom/client/dapp_chain_rpc_client.go:73 +0x5b
github.com/loomnetwork/go-loom/cli.ResolveAddress(0x50182df, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x107490f66b3a981, 0xc00091d950)
        /Users/gakonst/go/src/github.com/loomnetwork/go-loom/cli/util.go:41 +0x9a
github.com/loomnetwork/go-loom/cli.contract(0x50182df, 0x6, 0x9, 0xc00091da58, 0x400e5cf)
        /Users/gakonst/go/src/github.com/loomnetwork/go-loom/cli/cli.go:78 +0xfb
github.com/loomnetwork/go-loom/cli.StaticCallContract(0x50182df, 0x6, 0x5025600, 0xe, 0x533e6c0, 0xc000956d80, 0x4f5b5c0, 0xc00015bd80, 0x5016475, 0x4)
        /Users/gakonst/go/src/github.com/loomnetwork/go-loom/cli/cli.go:104 +0x4d
github.com/loomnetwork/go-loom/builtin/commands.ListValidatorsCmdV2.func1(0xc000924280, 0xc000956d40, 0x0, 0x2, 0x0, 0x0)
        /Users/gakonst/go/src/github.com/loomnetwork/go-loom/builtin/commands/dposV2_commands.go:73 +0xa8
github.com/spf13/cobra.(*Command).execute(0xc000924280, 0xc000956ce0, 0x2, 0x2, 0xc000924280, 0xc000956ce0)
        /Users/gakonst/go/src/github.com/spf13/cobra/command.go:762 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0x5e546c0, 0xc00096f680, 0xc00096f680, 0xc00096f900)
        /Users/gakonst/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x5e546c0, 0xc00091dea0, 0x1d)
        /Users/gakonst/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
```

We should either be returning an error, or prefix the string properly.

**Comment by enlight** [comment]
Resolved in https://github.com/loomnetwork/go-loom/pull/417
